let
  Source = Csv.Document(File.Contents(#"PODAJ ŚCIEŻKĘ FOLDERU"&"geografia.csv"), [Delimiter = ",", Encoding = 65001]),
    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"IDGeografii", type text}, {"Region", type text}, {"Centrala", type text}, {"MenedzerRegionalny", type text}})
in
    #"Changed Type"