let
    Source = Csv.Document(File.Contents(#"PODAJ ŚCIEŻKĘ FOLDERU" & "sprzedaz_surowa_v2.csv"),[Delimiter=",", Columns=16, Encoding=65001, QuoteStyle=QuoteStyle.None]),
    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    #"Changed Type with Locale" = Table.TransformColumnTypes(#"Promoted Headers", {{"DataWysylki", type date}}, "pl-PL"),
    #"Changed Type with Locale1" = Table.TransformColumnTypes(#"Changed Type with Locale", {{"DataSprzedazy", type date}}, "pl-PL"),
    #"Changed Type" = Table.TransformColumnTypes(#"Changed Type with Locale1",{{"Ilosc", Int64.Type}}),
    #"Changed Type with Locale2" = Table.TransformColumnTypes(#"Changed Type", {{"CenaJednostkowa", type number}}, "en-US"),
    Custom1 = Table.TransformColumnTypes(#"Changed Type with Locale2", {{"Rabat", type number}}, "en-US"),
    #"Changed Type with Locale3" = Table.TransformColumnTypes(Custom1, {{"KosztJednostkowy", type number}}, "en-US"),
    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Changed Type with Locale3", {"DataSprzedazy"}),
    #"Removed Other Columns" = Table.SelectColumns(#"Removed Errors",{"IDTransakcji", "DataSprzedazy", "DataWysylki", "IDKanalu", "Ilosc", "CenaJednostkowa", "Rabat", "KosztJednostkowy", "ProduktSurowy", "KlientSurowy", "Region", "StatusZamowienia", "NotatkaTechniczna", "Kanal", "TypKanalu"}),
    #"Extracted Text Before Delimiter" = Table.TransformColumns(#"Removed Other Columns", {{"KlientSurowy", each Text.BeforeDelimiter(_, "  ;"), type text}}),
    #"Trimmed Text" = Table.TransformColumns(#"Extracted Text Before Delimiter",{{"KlientSurowy", Text.Trim, type text}}),
    #"Extracted Text After Delimiter" = Table.TransformColumns(#"Trimmed Text", {{"KlientSurowy", each Text.AfterDelimiter(_, " "), type text}}),
    #"Renamed Columns" = Table.RenameColumns(#"Extracted Text After Delimiter",{{"KlientSurowy", "IDKlienta"}}),
    #"Added Prefix" = Table.TransformColumns(#"Renamed Columns", {{"IDKlienta", each "K" & _, type text}}),
    #"Inserted Text Before Delimiter" = Table.AddColumn(#"Added Prefix", "IDProduktu", each Text.BeforeDelimiter([ProduktSurowy], " | "), type text),
    #"Trimmed Text1" = Table.TransformColumns(#"Inserted Text Before Delimiter",{{"IDProduktu", Text.Trim, type text}}),
    #"Removed Columns" = Table.RemoveColumns(#"Trimmed Text1",{"ProduktSurowy"}),
    #"Replaced Value" = Table.ReplaceValue(#"Removed Columns"," ","",Replacer.ReplaceText,{"Region"}),
    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",".Zachód","Zachód",Replacer.ReplaceText,{"Region"}),
    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","Południe.","Południe",Replacer.ReplaceText,{"Region"}),
    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","Połud.nie","Południe",Replacer.ReplaceText,{"Region"}),
    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","/","",Replacer.ReplaceText,{"Region"}),
    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","Polnoc","Północ",Replacer.ReplaceText,{"Region"}),
    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5","realiz.","Zrealizowane",Replacer.ReplaceText,{"StatusZamowienia"}),
    #"Capitalized Each Word" = Table.TransformColumns(#"Replaced Value6",{{"StatusZamowienia", Text.Proper, type text}}),
    #"Replaced Value7" = Table.ReplaceValue(#"Capitalized Each Word","Zrealizowane","Done",Replacer.ReplaceText,{"StatusZamowienia"}),
    #"Replaced Value8" = Table.ReplaceValue(#"Replaced Value7","Anulowane","Cancelled",Replacer.ReplaceText,{"StatusZamowienia"}),
    #"Replaced Value9" = Table.ReplaceValue(#"Replaced Value8","W Realizacji","In progress",Replacer.ReplaceText,{"StatusZamowienia"}),
    #"Replaced Value10" = Table.ReplaceValue(#"Replaced Value9","","0",Replacer.ReplaceValue,{"Rabat"}),
    #"Added Custom" = Table.AddColumn(#"Replaced Value10", "Check", each if [StatusZamowienia] = "Cancelled" and [Kanal] = "Online" and [Rabat] = 0 then 1 else 0),
    #"Filtered Rows" = Table.SelectRows(#"Added Custom", each ([Check] = 0)),
    #"Removed Columns1" = Table.RemoveColumns(#"Filtered Rows",{"Check", "NotatkaTechniczna"}),
    #"Removed Duplicates" = Table.Distinct(#"Removed Columns1", {"IDTransakcji"})
in
    #"Removed Duplicates"